# name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
       node-version: 14
      - name: Install node modules
        run: npm install
          #Download and install yarn package manager
      - name: Prepare for Yarn Installation
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: Build React App
        run: yarn build
          
      # Will install Surge on runner, using run command
      - name: Install Surge
        run: npm install -g surge
        
      # Will run surge and deploy the application with provided name and surge token on runner
      - name: Run surge
        run : surge ./reactfirst/ positronFirstreactapp.surge.sh --token ${{secrets.FIRST_REACT}}
    
